version: '3.8'

networks:
  #
  # Public Network
  #
  publicWeb:

  minecraftNetwork:

  #
  # Prometheus Internal Network
  #
  prometheusNetwork:
  
  #
  # Minio intercommunication network
  #
  internalMinio:

configs:
  #
  # Public Reverse Proxy Caddyfile
  #
  WebConfig:
    name: Caddyfile-13
    file: ./Configs/Web/Caddyfile.json

  #
  # Minio Reverse Proxy Caddyfile
  #
  MinioWebConfig:
    name: MinioWebConfig-1
    file: ./Configs/MinioWeb/Caddyfile.json

  #
  # Prometheus Configuration File
  #
  PrometheusConfig:
    name: PrometheusConfig-7
    file: ./Configs/Prometheus/prometheus.yml
  
  GrafanaConfig:
    name: GrafanaConfig-5
    file: ./Configs/Prometheus/Grafana/grafana.ini

  GrafanaDatasources:
    name: GrafanaDatasources-2
    file: ./Configs/Prometheus/Grafana/datasource.yml

  GrafanaDashboardConfig:
    name: GrafanaDashboardConfig-1
    file: ./Configs/Prometheus/Grafana/dashboard.yml

  GrafanaKNetCADashboard:
    name: GrafanaKNetCADashboard-1
    file: ./Configs/Prometheus/Grafana/dashboards/Domains/knetca.json

  SSLExporterConfig:
    name: SSLExporterConfig-1
    file: ./Configs/Prometheus/SSLExporter/SSLExporter.yml

  GrafanaMinecraftTemplateDashboard:
    name: GrafanaMinecraftTemplateDashboard-12
    file: ./Configs/Prometheus/Grafana/dashboards/Minecraft/MinecraftTemplate.json

volumes:
  minio1Data:
    name: minio1Data
    external: true

  minio2Data:
    name: minio2Data
    external: true

  minio3Data:
    name: minio3Data
    external: true

  minio4Data:
    name: minio4Data
    external: true

  prometheusData:
    name: prometheusdata
    external: true

  #
  # Grafana Dashboard
  #
  grafanaData:
    name: grafanadata
    external: true

services:
  #
  # Reverse Proxy Handling all Web Traffic
  #
  Web:
    image: kristianfoss/programs-caddy:caddy-main-scratch
    command: ['run', '--config', '/etc/caddy/Caddyfile.json']
    configs:
      - source: WebConfig
        target: /etc/caddy/Caddyfile.json
    deploy:
      replicas: 6
    env_file: ENVs/Web.env
    networks:
      - publicWeb
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: ingress
      - target: 4843
        published: 443
        protocol: tcp
        mode: ingress
      - target: 8443
        published: 443
        protocol: udp
        mode: ingress
  #
  # Database
  #

  #
  # Minecraft
  #
  #
  # minecraft:
  #   image: itzg/minecraft-server
  #   restart: unless-stopped
  #   volumes:
  #     - minecraftData:/data
  #   ports:
  #     - 25565:25565/tcp
  #     - 25565:25565/udp
  #   environment:
  #     VERSION: latest
  #     EULA: 'TRUE'
  #     OVERRIDE_SERVER_PROPERTIES: 'true'
  #     OPS: KristianFJones
  #     ENABLE_QUERY: 'true'
  #     SPAWN_PROTECTION: '0'
  #     DIFFICULTY: hard
  #     USE_AIKAR_FLAGS: 'true'
  #     MOTD: '1.16.2 MC Server'
  #   labels:
  #     com.ouroboros.enable: 'true'

  #
  # Prometheus Monitoring System
  #
  Prometheus:
    image: kristianfoss/programs-prometheus:prometheus-server-main-scratch
    command:
      [
        '--storage.tsdb.path=/data',
        '--config.file=/etc/prometheus/prometheus.yml',
      ]
    configs:
      - source: PrometheusConfig
        target: /etc/prometheus/prometheus.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
    volumes:
      - prometheusData:/data
    networks:
      - publicWeb
      - prometheusNetwork

  #
  # Grafana Dashboard
  #
  Grafana:
    image: grafana/grafana
    configs:
      - source: GrafanaConfig
        target: /usr/share/grafana/conf/defaults.ini
      - source: GrafanaDatasources
        target: /etc/grafana/provisioning/datasources/datasource.yml
      - source: GrafanaDashboardConfig
        target: /etc/grafana/provisioning/dashboards/dashboard.yml
      - source: GrafanaKNetCADashboard
        target: /etc/grafana/provisioning/dashboards/knetca.json
      - source: GrafanaMinecraftTemplateDashboard
        target: /etc/grafana/provisioning/dashboards/mc-template.json
    volumes:
      - grafanaData:/var/lib/grafana
    networks:
      - publicWeb
      - prometheusNetwork

  SSLExporter:
    image: kristianfoss/programs-ssl-prometheus-exporter:main-scratch
    command: ['--config.file=/etc/ssl-exporter/ssl-exporter.yml']
    configs:
      - source: SSLExporterConfig
        target: /etc/ssl-exporter/ssl-exporter.yml
    networks:
      - prometheusNetwork

  DomainExporter:
    image: kristianfoss/programs-domain-prometheus-exporter:main-scratch
    networks:
      - prometheusNetwork

  #
  # Minio 
  #
  # Shared storage between Nodes
  #


  MinioWeb:
    image: kristianfoss/programs-caddy:caddy-main-scratch
    command: ['run', '--config', '/etc/caddy/Caddyfile.json']
    configs:
      - source: MinioWebConfig
        target: /etc/caddy/Caddyfile.json
        uid: '1000'
        gid: '1000'
        mode: 0440
    deploy:
      mode: replicated
      replicas: 6
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    networks:
      - internalMinio
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress

  Minio1:
    image: kristianfoss/programs-minio:minio-build-main-scratch
    command: ['server', 'http://Minio{1...4}/export']
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.hostname==vm1"
    env_file: ENVs/Minio.env
    volumes:
      - minio1Data:/export
    networks:
      - internalMinio

  Minio2:
    image: kristianfoss/programs-minio:minio-build-main-scratch
    command: ['server', 'http://Minio{1...4}/export']
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.hostname==vm2"
    env_file: ENVs/Minio.env
    volumes:
      - minio2Data:/export
    networks:
      - internalMinio

  Minio3:
    image: kristianfoss/programs-minio:minio-build-main-scratch
    command: ['server', 'http://Minio{1...4}/export']
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.hostname==vm3"
    env_file: ENVs/Minio.env
    volumes:
      - minio3Data:/export
    networks:
      - internalMinio

  Minio4:
    image: kristianfoss/programs-minio:minio-build-main-scratch
    command: ['server', 'http://Minio{1...4}/export']
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    env_file: ENVs/Minio.env
    volumes:
      - minio4Data:/export
    networks:
      - internalMinio
