global:
  scrape_interval: 1m
  evaluation_interval: 1m

  external_labels:
    monitor: 'KJDev.Azure1'

scrape_configs:
  - job_name: tls
    metrics_path: /probe
    scrape_interval: 12h
    static_configs:
      - targets:
          - knet.ca:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: SSLExporter:9219

  - job_name: network-exporter
    static_configs:
      - targets: ['NetworkExporter:9427']
    relabel_configs:
      - source_labels: [__address__]
        target_label: host
        regex: (.*):\d+
        replacement: ${1}

  - job_name: domain
    metrics_path: /probe
    scrape_interval: 12h
    static_configs:
      - targets:
          - knet.ca
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: DomainExporter:9222

  - job_name: federate-kjdev-int
    scrape_interval: 5m

    honor_labels: true
    metrics_path: /federate

    params:
      'match[]':
        - '{job="emmc1"}'
        - '{job="minio-job"}'
        - '{job="vmware-job"}'

    static_configs:
      - targets:
        - '66.165.222.180:9090'