global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: tls
    metrics_path: /probe
    static_configs:
      - targets:
          - knet.ca:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: SSLExporter:9219

  - job_name: domain
    metrics_path: /probe
    static_configs:
      - targets:
          - knet.ca
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: DomainExporter:9222

  - job_name: federate-kjdev-int
    scrape_interval: 15s

    honor_labels: true
    metrics_path: /federate

    params:
      'match[]':
        - '{job="emmc1"}'

    static_configs:
      - targets:
        - '66.165.222.180:9090'